import { CaseData } from "./LinkedList";

export const sampleCases: CaseData[] = [
  {
    caseId: "CASE-001",
    title: "Warehouse Break-in",
    description: "Forced entry at Harbor District warehouse. Surveillance footage shows two suspects.",
    priority: "High",
    status: "Open",
    suspectName: "Marcus Webb",
    date: "2026-04-01",
  },
  {
    caseId: "CASE-002",
    title: "Identity Theft Ring",
    description: "Multiple victims report stolen credentials used for fraudulent bank transfers.",
    priority: "High",
    status: "Open",
    suspectName: "Elena Vasquez",
    date: "2026-03-28",
  },
  {
    caseId: "CASE-003",
    title: "Vehicle Theft - Downtown",
    description: "Series of luxury vehicle thefts near financial district parking garages.",
    priority: "Medium",
    status: "Open",
    suspectName: "Marcus Webb",
    date: "2026-03-25",
  },
  {
    caseId: "CASE-004",
    title: "Cyber Fraud Investigation",
    description: "Phishing campaign targeting corporate employees. Linked to overseas operations.",
    priority: "High",
    status: "Open",
    suspectName: "Elena Vasquez",
    date: "2026-04-05",
  },
  {
    caseId: "CASE-005",
    title: "Vandalism at City Hall",
    description: "Property damage during overnight hours. Security guard reports suspicious activity.",
    priority: "Low",
    status: "Closed",
    suspectName: "Jordan Blake",
    date: "2026-02-14",
  },
  {
    caseId: "CASE-006",
    title: "Drug Trafficking Tip",
    description: "Anonymous tip about narcotics distribution network operating through local businesses.",
    priority: "High",
    status: "Open",
    suspectName: "Marcus Webb",
    date: "2026-04-08",
  },
  {
    caseId: "CASE-007",
    title: "Missing Evidence Report",
    description: "Evidence locker discrepancy discovered during routine audit. Internal investigation needed.",
    priority: "Medium",
    status: "Open",
    suspectName: "Unknown",
    date: "2026-03-15",
  },
  {
    caseId: "CASE-008",
    title: "Financial Fraud Scheme",
    description: "Ponzi scheme targeting elderly residents. Multiple bank accounts flagged for suspicious transfers.",
    priority: "High",
    status: "Open",
    suspectName: "Elena Vasquez",
    date: "2026-04-03",
  },
];
