import { CaseData } from "./LinkedList";

export const sampleCases: CaseData[] = [
  {
    caseId: "CASE-001",
    title: "Warehouse Break-in & Grand Larceny",
    description: "Forced midnight breach at Harbor District logistics facility. Specialized cutting torches used on high-security vault containing bonded electronic components.",
    category: "Theft",
    priority: "High",
    status: "Under Investigation",
    suspectName: "Marcus Webb",
    investigator: "Det. Sarah Vance",
    date: "2026-04-01",
    deadline: "2026-04-15",
    progress: 65,
    location: "Pier 42, Harbor Logistics Terminal",
    tags: ["Burglary", "Commercial", "Forensics", "Surveillance"],
  },
  {
    caseId: "CASE-002",
    title: "Identity Theft Ring & Synthetic IDs",
    description: "Coordinated syndicate manufacturing synthetic identities to open fraudulent accounts and siphon offshore funds via encrypted relays.",
    category: "Fraud",
    priority: "Critical",
    status: "Under Investigation",
    suspectName: "Elena Vasquez",
    investigator: "Agent David Chen",
    date: "2026-03-28",
    deadline: "2026-04-12",
    progress: 80,
    location: "Apex Financial Tower, Suite 900",
    tags: ["Cybercrime", "Banking", "Synthetic ID", "FinCEN"],
  },
  {
    caseId: "CASE-003",
    title: "Luxury Vehicle Theft Syndicate",
    description: "Series of high-end commercial fleet and private armored vehicle thefts near financial district parking garages using CAN-bus injection tools.",
    category: "Theft",
    priority: "Medium",
    status: "Under Investigation",
    suspectName: "Marcus Webb",
    investigator: "Det. Sarah Vance",
    date: "2026-03-25",
    deadline: "2026-04-20",
    progress: 45,
    location: "Midtown Financial Underground Garage",
    tags: ["Auto-Theft", "Keyless Replay", "Chop Shop"],
  },
  {
    caseId: "CASE-004",
    title: "Corporate Spear-Phishing & Wire Fraud",
    description: "Phishing campaign targeting corporate finance executives. Wire transfers redirected to offshore shell entities in Cyprus.",
    category: "Cyber",
    priority: "High",
    status: "Under Investigation",
    suspectName: "Elena Vasquez",
    investigator: "Agent David Chen",
    date: "2026-04-05",
    deadline: "2026-04-18",
    progress: 70,
    location: "Northstar Tech Campus, Bldg 4",
    tags: ["BEC", "Phishing", "Wire Fraud", "Foreign Relays"],
  },
  {
    caseId: "CASE-005",
    title: "Municipal Building Vandalism & Intrusion",
    description: "Overnight perimeter breach and server room tampering at City Hall. Data terminals physically unlocked and exterior surveillance cameras spray-painted.",
    category: "Vandalism",
    priority: "Low",
    status: "Closed",
    suspectName: "Jordan Blake",
    investigator: "Officer Ray Miller",
    date: "2026-02-14",
    deadline: "2026-03-01",
    progress: 100,
    location: "Civic Plaza, Metro City Hall",
    tags: ["Physical Security", "Trespassing", "Closed"],
  },
  {
    caseId: "CASE-006",
    title: "Maritime Narcotics Smuggling Nexus",
    description: "Intelligence tip regarding commercial cargo vessel container tampering and distribution through local front logistics firms.",
    category: "Narcotics",
    priority: "Critical",
    status: "Under Investigation",
    suspectName: "Marcus Webb",
    investigator: "Det. Sarah Vance",
    date: "2026-04-08",
    deadline: "2026-04-22",
    progress: 85,
    location: "East Coast Container Terminal Berth 7",
    tags: ["Maritime", "Narcotics", "DEA Liaison", "Interdiction"],
  },
  {
    caseId: "CASE-007",
    title: "Missing Evidence Report & Locker Discrepancy",
    description: "Evidence locker discrepancy discovered during routine quarterly audit. Unlogged chain of custody transfer of encrypted storage drives.",
    category: "Intelligence",
    priority: "Medium",
    status: "New",
    suspectName: "Unknown",
    investigator: "Internal Affairs Insp. Novak",
    date: "2026-03-15",
    deadline: "2026-04-30",
    progress: 20,
    location: "Central Precinct Headquarters",
    tags: ["Internal Affairs", "Chain of Custody", "Audit"],
  },
  {
    caseId: "CASE-008",
    title: "Offshore Ponzi & Securities Fraud Scheme",
    description: "Multi-jurisdictional securities scheme soliciting investments into bogus green energy trusts through shell advisory firms.",
    category: "Financial",
    priority: "High",
    status: "Under Investigation",
    suspectName: "Elena Vasquez",
    investigator: "Agent David Chen",
    date: "2026-04-03",
    deadline: "2026-04-25",
    progress: 60,
    location: "Grand Cayman / Metro Financial District",
    tags: ["Securities", "Money Laundering", "Shell Companies"],
  },
  {
    caseId: "CASE-009",
    title: "Dark Web Data Brokerage Exfiltration",
    description: "Proprietary algorithmic trading models exfiltrated from tech infrastructure and offered on darknet breach forums.",
    category: "Cyber",
    priority: "Critical",
    status: "Under Investigation",
    suspectName: "Kaelen Cross",
    investigator: "Agent David Chen",
    date: "2026-04-07",
    deadline: "2026-04-19",
    progress: 40,
    location: "Quantum Trading Server Farm",
    tags: ["Insider Threat", "Dark Web", "IP Theft"],
  },
  {
    caseId: "CASE-010",
    title: "Cargo Manifest Forgery & Customs Diversion",
    description: "Falsified maritime bills of lading routing high-value dual-use telecommunication hardware away from inspected ports.",
    category: "Fraud",
    priority: "Medium",
    status: "Under Investigation",
    suspectName: "Jordan Blake",
    investigator: "Det. Sarah Vance",
    date: "2026-04-05",
    deadline: "2026-04-28",
    progress: 30,
    location: "Port Authority Cargo Gate 12",
    tags: ["Customs", "Manifest", "Export Control"],
  },
];

export const sampleEntities = [
  { entityId: 'ENT-001', name: 'Marcus Webb', type: 'Person', description: 'Primary subject in logistics burglary & vehicle ring', riskLevel: 'Critical', relatedCases: ['CASE-001', 'CASE-003', 'CASE-006'] },
  { entityId: 'ENT-002', name: 'Elena Vasquez', type: 'Person', description: 'Financier & director of Apex Holdings Ltd', riskLevel: 'Critical', relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'] },
  { entityId: 'ENT-003', name: 'Jordan Blake', type: 'Person', description: 'Harbor logistics dispatcher and manifest clerk', riskLevel: 'Medium', relatedCases: ['CASE-005', 'CASE-010'] },
  { entityId: 'ENT-004', name: 'Kaelen Cross', type: 'Person', description: 'Systems engineer suspected of trade model theft', riskLevel: 'High', relatedCases: ['CASE-009'] },
  { entityId: 'ENT-005', name: 'Apex Holdings Ltd', type: 'Organization', description: 'Delaware shell company holding overseas bank accounts', riskLevel: 'Critical', relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'] },
  { entityId: 'ENT-006', name: 'Harbor Logistics Freight Co.', type: 'Organization', description: 'Pier 42 freight terminal operator', riskLevel: 'High', relatedCases: ['CASE-001', 'CASE-006'] },
  { entityId: 'ENT-007', name: 'Pier 42 Harbor Warehouse', type: 'Location', description: 'Crime scene of electronic components break-in', riskLevel: 'Medium', relatedCases: ['CASE-001', 'CASE-006'] },
  { entityId: 'ENT-008', name: 'Apex Financial Tower', type: 'Location', description: 'Corporate office suites for Vasquez operations', riskLevel: 'High', relatedCases: ['CASE-002', 'CASE-008'] },
  { entityId: 'ENT-009', name: 'Black BMW M5 (Plates: 7XYZ-89)', type: 'Vehicle', description: 'Getaway vehicle recorded on CCTV leaving Pier 42', riskLevel: 'High', relatedCases: ['CASE-001', 'CASE-003'] },
  { entityId: 'ENT-010', name: 'Encrypted Burner Phone (+1-555-438-9021)', type: 'Phone', description: 'Hardened satellite handset recovered from scene', riskLevel: 'High', relatedCases: ['CASE-001', 'CASE-003', 'CASE-006'] },
  { entityId: 'ENT-011', name: 'Encrypted Proton Email (v_elena@pm.me)', type: 'Email', description: 'Mail account used to coordinate wire redirects', riskLevel: 'High', relatedCases: ['CASE-002', 'CASE-004'] },
  { entityId: 'ENT-012', name: 'Wire Transfer #WT-89410 ($1.25M)', type: 'Transaction', description: 'Transfer from Apex Holdings to Zurich mercantile bank', riskLevel: 'Critical', relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'] },
  { entityId: 'ENT-013', name: 'Crypto Wallet 0x71C...4F9B (USDT)', type: 'Transaction', description: 'Tether address receiving stolen vehicle payouts', riskLevel: 'High', relatedCases: ['CASE-003', 'CASE-009'] },
  { entityId: 'ENT-014', name: 'Falsified Bill of Lading BL-4901', type: 'Document', description: 'Forged customs documentation declaring false weights', riskLevel: 'High', relatedCases: ['CASE-006', 'CASE-010'] },
  { entityId: 'ENT-015', name: 'Recovered Thermal Cutting Rig', type: 'Evidence', description: 'Exothermic oxygen lance found near pier canal', riskLevel: 'Medium', relatedCases: ['CASE-001'] },
  { entityId: 'ENT-016', name: 'CAN-Bus Spoofing Hardware', type: 'Evidence', description: 'Immobilizer bypass tool recovered from suspect vehicle', riskLevel: 'High', relatedCases: ['CASE-003'] },
  { entityId: 'ENT-017', name: 'Northstar Tech Campus', type: 'Location', description: 'Commercial tech campus targeted in spear phishing', riskLevel: 'Low', relatedCases: ['CASE-004', 'CASE-009'] },
  { entityId: 'ENT-018', name: 'East Coast Container Berth 7', type: 'Location', description: 'Deepwater dock where contraband cargo was offloaded', riskLevel: 'High', relatedCases: ['CASE-006', 'CASE-010'] },
  { entityId: 'ENT-019', name: 'Freightliner Heavy Hauler (Plates: 4TRK-01)', type: 'Vehicle', description: 'Flatbed transport used for container transfers', riskLevel: 'Medium', relatedCases: ['CASE-001', 'CASE-006'] },
  { entityId: 'ENT-020', name: 'Encrypted USB Storage Key (Kingston IronKey)', type: 'Evidence', description: 'Cryptographic storage device holding identity dumps', riskLevel: 'Critical', relatedCases: ['CASE-002', 'CASE-007'] },
  { entityId: 'ENT-021', name: 'Vessel MV Northern Star', type: 'Vehicle', description: 'Panamanian container freighter docked at Berth 7', riskLevel: 'High', relatedCases: ['CASE-006', 'CASE-010'] },
  { entityId: 'ENT-022', name: 'Midtown Underground Garage', type: 'Location', description: 'Parking facility targeted in vehicle thefts', riskLevel: 'Low', relatedCases: ['CASE-003'] },
];

export const sampleRelationships = [
  { relationshipId: 'REL-001', sourceEntity: 'Marcus Webb', targetEntity: 'Encrypted Burner Phone (+1-555-438-9021)', type: 'Owned by', strength: 'strong', caseId: 'CASE-001', details: 'Handset found in subject possession' },
  { relationshipId: 'REL-002', sourceEntity: 'Encrypted Burner Phone (+1-555-438-9021)', targetEntity: 'Elena Vasquez', type: 'Contacted', strength: 'strong', caseId: 'CASE-001', details: '14 encrypted communications logged' },
  { relationshipId: 'REL-003', sourceEntity: 'Marcus Webb', targetEntity: 'Harbor Logistics Freight Co.', type: 'Associated with', strength: 'strong', caseId: 'CASE-001', details: 'Contractor pass issued to Webb alias' },
  { relationshipId: 'REL-004', sourceEntity: 'Marcus Webb', targetEntity: 'Black BMW M5 (Plates: 7XYZ-89)', type: 'Contacted', strength: 'strong', caseId: 'CASE-001', details: 'Recorded operating vehicle on surveillance' },
  { relationshipId: 'REL-005', sourceEntity: 'Black BMW M5 (Plates: 7XYZ-89)', targetEntity: 'Apex Holdings Ltd', type: 'Owned by', strength: 'strong', caseId: 'CASE-001', details: 'Corporate lease held by Apex Holdings' },
  { relationshipId: 'REL-006', sourceEntity: 'Apex Holdings Ltd', targetEntity: 'Elena Vasquez', type: 'Owned by', strength: 'strong', caseId: 'CASE-002', details: 'Elena Vasquez listed as sole director' },
  { relationshipId: 'REL-007', sourceEntity: 'Elena Vasquez', targetEntity: 'Apex Financial Tower', type: 'Located at', strength: 'strong', caseId: 'CASE-002', details: 'Executive Suite 900 lease' },
  { relationshipId: 'REL-008', sourceEntity: 'Elena Vasquez', targetEntity: 'Encrypted Proton Email (v_elena@pm.me)', type: 'Associated with', strength: 'strong', caseId: 'CASE-002', details: 'Primary corporate contact email' },
  { relationshipId: 'REL-009', sourceEntity: 'Apex Holdings Ltd', targetEntity: 'Wire Transfer #WT-89410 ($1.25M)', type: 'Transferred to', strength: 'strong', caseId: 'CASE-002', details: 'Direct outflow remittance' },
  { relationshipId: 'REL-010', sourceEntity: 'Marcus Webb', targetEntity: 'Pier 42 Harbor Warehouse', type: 'Located at', strength: 'strong', caseId: 'CASE-001', details: 'Cell ping at 01:12 AM' },
  { relationshipId: 'REL-011', sourceEntity: 'Pier 42 Harbor Warehouse', targetEntity: 'Recovered Thermal Cutting Rig', type: 'Evidence of', strength: 'strong', caseId: 'CASE-001', details: 'Tool found 300m from vault breach' },
  { relationshipId: 'REL-012', sourceEntity: 'Marcus Webb', targetEntity: 'Midtown Underground Garage', type: 'Located at', strength: 'moderate', caseId: 'CASE-003', details: 'Gait match on CCTV' },
  { relationshipId: 'REL-013', sourceEntity: 'Marcus Webb', targetEntity: 'CAN-Bus Spoofing Hardware', type: 'Associated with', strength: 'strong', caseId: 'CASE-003', details: 'Latent fingerprint identified' },
  { relationshipId: 'REL-014', sourceEntity: 'Elena Vasquez', targetEntity: 'Northstar Tech Campus', type: 'Mentioned in', strength: 'moderate', caseId: 'CASE-004', details: 'Sender credential impersonated' },
  { relationshipId: 'REL-015', sourceEntity: 'Marcus Webb', targetEntity: 'Jordan Blake', type: 'Connected through', strength: 'strong', caseId: 'CASE-006', details: 'Regular phone contact before shifts' },
  { relationshipId: 'REL-016', sourceEntity: 'Jordan Blake', targetEntity: 'Harbor Logistics Freight Co.', type: 'Associated with', strength: 'strong', caseId: 'CASE-006', details: 'Gate dispatcher position' },
  { relationshipId: 'REL-017', sourceEntity: 'Jordan Blake', targetEntity: 'Falsified Bill of Lading BL-4901', type: 'Evidence of', strength: 'strong', caseId: 'CASE-010', details: 'Signed under Blake terminal ID' },
  { relationshipId: 'REL-018', sourceEntity: 'Falsified Bill of Lading BL-4901', targetEntity: 'Vessel MV Northern Star', type: 'Related to', strength: 'strong', caseId: 'CASE-006', details: 'Covers vessel cargo hold unit' },
  { relationshipId: 'REL-019', sourceEntity: 'Vessel MV Northern Star', targetEntity: 'East Coast Container Berth 7', type: 'Located at', strength: 'strong', caseId: 'CASE-006', details: 'Docking log berth 7' },
  { relationshipId: 'REL-020', sourceEntity: 'Jordan Blake', targetEntity: 'Freightliner Heavy Hauler (Plates: 4TRK-01)', type: 'Contacted', strength: 'moderate', caseId: 'CASE-006', details: 'Dispatched flatbed without gate scan' },
  { relationshipId: 'REL-021', sourceEntity: 'Elena Vasquez', targetEntity: 'Encrypted USB Storage Key (Kingston IronKey)', type: 'Owned by', strength: 'strong', caseId: 'CASE-002', details: 'Device serial listed on office inventory' },
  { relationshipId: 'REL-022', sourceEntity: 'Kaelen Cross', targetEntity: 'Northstar Tech Campus', type: 'Associated with', strength: 'strong', caseId: 'CASE-009', details: 'Former employee access logs' },
  { relationshipId: 'REL-023', sourceEntity: 'Kaelen Cross', targetEntity: 'Crypto Wallet 0x71C...4F9B (USDT)', type: 'Transferred to', strength: 'strong', caseId: 'CASE-009', details: 'Direct withdrawal recipient' },
  { relationshipId: 'REL-024', sourceEntity: 'Elena Vasquez', targetEntity: 'Crypto Wallet 0x71C...4F9B (USDT)', type: 'Connected through', strength: 'moderate', caseId: 'CASE-004', details: 'Interacted with affiliated smart contract' },
  { relationshipId: 'REL-025', sourceEntity: 'Marcus Webb', targetEntity: 'East Coast Container Berth 7', type: 'Located at', strength: 'strong', caseId: 'CASE-006', details: 'Observed meeting crew members' },
  { relationshipId: 'REL-026', sourceEntity: 'Wire Transfer #WT-89410 ($1.25M)', targetEntity: 'Elena Vasquez', type: 'Related to', strength: 'strong', caseId: 'CASE-008', details: 'Signed authorization memorandum' },
];

export const sampleTimeline = [
  { eventId: 'EVT-001', caseId: 'CASE-001', date: '2026-03-24', time: '12:45 AM', eventType: 'Movement', description: 'Black BMW M5 detected idling outside Harbor Logistics Gate 4 perimeter fence.', relatedEntity: 'Black BMW M5 (Plates: 7XYZ-89)', location: 'Pier 42 Harbor Warehouse' },
  { eventId: 'EVT-002', caseId: 'CASE-001', date: '2026-03-24', time: '01:12 AM', eventType: 'Incident', description: 'Intrusion alarm tripped on Vault 4B; perimeter sensors cut with wire snips.', relatedEntity: 'Marcus Webb', location: 'Pier 42 Harbor Warehouse' },
  { eventId: 'EVT-003', caseId: 'CASE-001', date: '2026-03-24', time: '01:38 AM', eventType: 'Contact', description: 'Burner phone initiates encrypted outbound call to Elena Vasquez contact handle.', relatedEntity: 'Encrypted Burner Phone (+1-555-438-9021)', location: 'Harbor District' },
  { eventId: 'EVT-004', caseId: 'CASE-001', date: '2026-03-24', time: '04:15 AM', eventType: 'Evidence Upload', description: 'Physical recovery of abandoned thermal cutting torch and magnesium rod remnants.', relatedEntity: 'Recovered Thermal Cutting Rig', location: 'Pier 42 Drainage Canal' },
  { eventId: 'EVT-005', caseId: 'CASE-003', date: '2026-03-25', time: '09:10 PM', eventType: 'Incident', description: 'Two luxury SUVs stolen from Midtown garage using electronic signal amplifier.', relatedEntity: 'Marcus Webb', location: 'Midtown Underground Garage' },
  { eventId: 'EVT-006', caseId: 'CASE-003', date: '2026-03-26', time: '11:00 AM', eventType: 'Evidence Upload', description: 'CAN-bus emulator board recovered from abandoned decoy vehicle on Route 9.', relatedEntity: 'CAN-Bus Spoofing Hardware', location: 'Route 9 Northbound' },
  { eventId: 'EVT-007', caseId: 'CASE-002', date: '2026-03-28', time: '09:30 AM', eventType: 'Transaction', description: 'Wire transfer #WT-89410 initiated from Apex Holdings account for $1.25M.', relatedEntity: 'Wire Transfer #WT-89410 ($1.25M)', location: 'Apex Financial Tower' },
  { eventId: 'EVT-008', caseId: 'CASE-002', date: '2026-03-28', time: '02:45 PM', eventType: 'Finding Added', description: 'Investigator discovers beneficial owner of Apex Holdings is Elena Vasquez.', relatedEntity: 'Elena Vasquez', location: 'Apex Financial Tower' },
  { eventId: 'EVT-009', caseId: 'CASE-004', date: '2026-03-29', time: '08:15 AM', eventType: 'Communication', description: 'Phishing campaign launched targeting 48 senior financial officers at Northstar Tech.', relatedEntity: 'Encrypted Proton Email (v_elena@pm.me)', location: 'Northstar Tech Campus' },
  { eventId: 'EVT-010', caseId: 'CASE-004', date: '2026-03-30', time: '04:20 PM', eventType: 'Finding Added', description: 'Cyber unit isolates malware payload confirming signature match to Specter_9 group.', relatedEntity: 'Elena Vasquez', location: 'Cyber Operations Center' },
  { eventId: 'EVT-011', caseId: 'CASE-005', date: '2026-04-01', time: '02:20 AM', eventType: 'Incident', description: 'Physical intrusion detected at City Hall basement terminals; Jordan Blake captured on camera.', relatedEntity: 'Jordan Blake', location: 'Civic Plaza, Metro City Hall' },
  { eventId: 'EVT-012', caseId: 'CASE-008', date: '2026-04-02', time: '01:00 PM', eventType: 'Interview', description: 'Subpoenaed bank compliance officer confirms Vasquez personal presence during account setups.', relatedEntity: 'Elena Vasquez', location: 'Federal Courthouse' },
  { eventId: 'EVT-013', caseId: 'CASE-006', date: '2026-04-04', time: '06:00 AM', eventType: 'Movement', description: 'Container ship MV Northern Star berths at East Coast Container Terminal Berth 7.', relatedEntity: 'Vessel MV Northern Star', location: 'East Coast Container Berth 7' },
  { eventId: 'EVT-014', caseId: 'CASE-006', date: '2026-04-04', time: '06:30 PM', eventType: 'Contact', description: 'Wiretap captures dispatcher Jordan Blake alerting Marcus Webb regarding customs schedule.', relatedEntity: 'Marcus Webb', location: 'Harbor Logistics Yard' },
  { eventId: 'EVT-015', caseId: 'CASE-006', date: '2026-04-05', time: '03:15 AM', eventType: 'Incident', description: 'Federal joint task force intercepts Container TGHU-992144; positive swab for narcotics.', relatedEntity: 'Marcus Webb', location: 'Port Authority Gate 12' },
];

export const sampleEvidence = [
  { evidenceId: 'EVD-001', name: 'Pier 42 Vault Door Cutting Swarf & Residue', type: 'Physical Evidence', description: 'Exothermic metal slag and magnesium wire fragments gathered from safe door perimeter.', caseId: 'CASE-001', uploadedBy: 'Forensics Specialist Ramos', status: 'Verified' },
  { evidenceId: 'EVD-002', name: 'CCTV Exterior Gate 4 Footage (MP4)', type: 'Video', description: 'High-definition 4K footage capturing black BMW M5 exiting compound without lights at 01:48 AM.', caseId: 'CASE-001', uploadedBy: 'Det. Sarah Vance', status: 'Verified' },
  { evidenceId: 'EVD-003', name: 'Burner Handset Cellular Tower Extraction (ZIP)', type: 'Digital Record', description: 'Full forensic extraction of VoLTE burner phone showing 42 contact records and encrypted SMS.', caseId: 'CASE-001', uploadedBy: 'Cyber Tech Lin', status: 'In Analysis' },
  { evidenceId: 'EVD-004', name: 'Apex Holdings Cayman Banking Subpoena Return', type: 'Document', description: 'Certified financial statements detailing $1.25M wire outflow and beneficial ownership.', caseId: 'CASE-002', uploadedBy: 'Agent David Chen', status: 'Verified' },
  { evidenceId: 'EVD-005', name: 'Synthetic Credit Application Packet (Batch #9)', type: 'Document', description: '45 fraudulent loan files utilizing fictitious social security numbers.', caseId: 'CASE-002', uploadedBy: 'Agent David Chen', status: 'Collected' },
  { evidenceId: 'EVD-006', name: 'CAN-Bus Inverter & Key Emulator Module', type: 'Digital Record', description: 'Captured hardware tool extracted from dashboard wiring harness of luxury SUV.', caseId: 'CASE-003', uploadedBy: 'Det. Sarah Vance', status: 'Verified' },
  { evidenceId: 'EVD-007', name: 'Midtown Garage Surveillance Tape Roll 3', type: 'Video', description: 'Overhead camera recording two individuals programming vehicle through OBD port.', caseId: 'CASE-003', uploadedBy: 'Officer Ray Miller', status: 'Collected' },
  { evidenceId: 'EVD-008', name: 'Phishing Email Header Logs & SPF Mismatch', type: 'Digital Record', description: 'Raw headers demonstrating DKIM forgery and originating IP belonging to VPN node.', caseId: 'CASE-004', uploadedBy: 'Cyber Tech Lin', status: 'Verified' },
  { evidenceId: 'EVD-009', name: 'City Hall Server Access Audit Dump', type: 'Document', description: 'Active Directory domain controller logs showing physical console logon attempts.', caseId: 'CASE-005', uploadedBy: 'Officer Ray Miller', status: 'Archived' },
  { evidenceId: 'EVD-010', name: 'Maritime Cargo Manifest BL-4901 Original', type: 'Document', description: 'Stamped hard-copy manifest with mismatched weight discrepancy (14.2t vs 28.5t).', caseId: 'CASE-006', uploadedBy: 'Det. Sarah Vance', status: 'Verified' },
  { evidenceId: 'EVD-011', name: 'Narcotics Swab Analysis Laboratory Report', type: 'Physical Evidence', description: 'Spectrometer confirmation of contraband on bulkheads of container TGHU-992144.', caseId: 'CASE-006', uploadedBy: 'DEA Forensic Lab', status: 'Verified' },
  { evidenceId: 'EVD-012', name: 'Internal Audit Custody Seal Photographs', type: 'Image', description: 'High-resolution images showing tampered barcode tape on evidence box in Locker 4B.', caseId: 'CASE-007', uploadedBy: 'Insp. Novak', status: 'Collected' },
  { evidenceId: 'EVD-013', name: 'Ponzi Investment Marketing Brochure & Contract', type: 'Document', description: 'Glossy pitch deck promising 28% annual fixed yield backed by bogus green energy.', caseId: 'CASE-008', uploadedBy: 'Agent David Chen', status: 'Verified' },
  { evidenceId: 'EVD-014', name: 'Breach Forum Telegram Chat Export', type: 'Digital Record', description: 'Scraped channel conversations between user Specter_9 and dark web broker.', caseId: 'CASE-009', uploadedBy: 'Agent David Chen', status: 'In Analysis' },
  { evidenceId: 'EVD-015', name: 'Kingston IronKey Decrypted Volume Image', type: 'Digital Record', description: 'Bitstream image copy containing 12,000 synthetic banking profiles.', caseId: 'CASE-002', uploadedBy: 'Cyber Tech Lin', status: 'Verified' },
];

export const sampleAlerts = [
  { alertId: 'ALT-001', type: 'critical' as const, title: 'Repeat Suspect Detected Across 3 Active Cases', message: 'Marcus Webb appears in CASE-001, CASE-003, and CASE-006. Serial nexus identified.', caseId: 'CASE-001', isRead: false },
  { alertId: 'ALT-002', type: 'critical' as const, title: 'High-Value Offshore Wire Transfer Flagged', message: 'Wire Transfer #WT-89410 for $1,250,000 matches FinCEN threshold alerts linked to Apex Holdings.', caseId: 'CASE-002', isRead: false },
  { alertId: 'ALT-003', type: 'high' as const, title: 'Multi-Case Network Hub: Elena Vasquez', message: 'Elena Vasquez connects 3 active high-priority cases (Synthetic ID, Corporate Fraud, Securities).', caseId: 'CASE-002', isRead: false },
  { alertId: 'ALT-004', type: 'high' as const, title: 'Container Interdiction Deadline Approaching', message: 'Statutory 72-hour detention hold on MV Northern Star container cargo expires in 28 hours.', caseId: 'CASE-006', isRead: false },
  { alertId: 'ALT-005', type: 'warning' as const, title: 'Chain-of-Custody Discrepancy Red-Flagged', message: 'Internal Affairs logged an audit mismatch on storage drive evidence in Central Locker 4B.', caseId: 'CASE-007', isRead: false },
  { alertId: 'ALT-006', type: 'warning' as const, title: 'CAN-Bus Hardware Match Identified', message: 'Spoofing microcontroller firmware recovered in CASE-003 matches tools previously seized.', caseId: 'CASE-003', isRead: true },
  { alertId: 'ALT-007', type: 'critical' as const, title: 'Classified Trade Algorithm Exfiltration Alert', message: 'Tor network broker post confirmed offering Northstar Tech trade models for Tether.', caseId: 'CASE-009', isRead: false },
  { alertId: 'ALT-008', type: 'info' as const, title: 'Municipal Intrusion Case Concluded', message: 'CASE-005 successfully resolved and archived with formal charges filed against Jordan Blake.', caseId: 'CASE-005', isRead: true },
  { alertId: 'ALT-009', type: 'high' as const, title: 'Decrypted IronKey Yields 12,000 Profiles', message: 'Digital forensics unit finalized full extraction of decrypted financial credentials.', caseId: 'CASE-002', isRead: false },
  { alertId: 'ALT-010', type: 'info' as const, title: 'Investigation Backlog Notice', message: '7 cases currently Under Investigation require milestone status review before end-of-month audit.', caseId: '', isRead: false },
];
