const Case = require('../models/Case');
const Entity = require('../models/Entity');
const Relationship = require('../models/Relationship');
const Evidence = require('../models/Evidence');
const TimelineEvent = require('../models/TimelineEvent');
const Investigation = require('../models/Investigation');
const Alert = require('../models/Alert');
const Activity = require('../models/Activity');

exports.seedDatabase = async (req, res) => {
  try {
    // Clear existing CaseChain data
    await Promise.all([
      Case.deleteMany({}),
      Entity.deleteMany({}),
      Relationship.deleteMany({}),
      Evidence.deleteMany({}),
      TimelineEvent.deleteMany({}),
      Investigation.deleteMany({}),
      Alert.deleteMany({}),
      Activity.deleteMany({}),
    ]);

    // 1. CASES (10 realistic fictional cases)
    const casesData = [
      {
        caseId: 'CASE-001',
        title: 'Warehouse Break-in & Grand Larceny',
        description: 'Forced midnight breach at Harbor District logistics facility. Specialized cutting torches used on high-security vault containing bonded electronic components.',
        category: 'Theft',
        priority: 'High',
        status: 'Under Investigation',
        suspectName: 'Marcus Webb',
        investigator: 'Det. Sarah Vance',
        deadline: new Date(Date.now() + 14 * 86400000),
        progress: 65,
        location: 'Pier 42, Harbor Logistics Terminal',
        tags: ['Burglary', 'Commercial', 'Forensics', 'Surveillance'],
      },
      {
        caseId: 'CASE-002',
        title: 'Identity Theft Ring & Synthetic IDs',
        description: 'Coordinated syndicate manufacturing synthetic identities to open fraudulent accounts and siphon offshore funds via encrypted relays.',
        category: 'Fraud',
        priority: 'Critical',
        status: 'Under Investigation',
        suspectName: 'Elena Vasquez',
        investigator: 'Agent David Chen',
        deadline: new Date(Date.now() + 7 * 86400000),
        progress: 80,
        location: 'Apex Financial Tower, Suite 900',
        tags: ['Cybercrime', 'Banking', 'Synthetic ID', 'FinCEN'],
      },
      {
        caseId: 'CASE-003',
        title: 'Luxury Vehicle Theft Syndicate',
        description: 'Targeted theft of high-end commercial fleet and private armored vehicles utilizing signal spoofing and CAN-bus injection tools.',
        category: 'Theft',
        priority: 'Medium',
        status: 'Under Investigation',
        suspectName: 'Marcus Webb',
        investigator: 'Det. Sarah Vance',
        deadline: new Date(Date.now() + 21 * 86400000),
        progress: 45,
        location: 'Midtown Financial Underground Garage',
        tags: ['Auto-Theft', 'Keyless Replay', 'Chop Shop'],
      },
      {
        caseId: 'CASE-004',
        title: 'Corporate Spear-Phishing & Wire Fraud',
        description: 'Targeted spear-phishing campaign impersonating executive officers to redirect $2.4M treasury transfers to shell entities in Cyprus.',
        category: 'Cyber',
        priority: 'High',
        status: 'Under Investigation',
        suspectName: 'Elena Vasquez',
        investigator: 'Agent David Chen',
        deadline: new Date(Date.now() + 10 * 86400000),
        progress: 70,
        location: 'Northstar Tech Campus, Bldg 4',
        tags: ['BEC', 'Phishing', 'Wire Fraud', 'Foreign Relays'],
      },
      {
        caseId: 'CASE-005',
        title: 'Municipal Building Vandalism & Intrusion',
        description: 'Overnight perimeter breach and server room tampering at City Hall. Data terminals physically unlocked and exterior surveillance cameras spray-painted.',
        category: 'Vandalism',
        priority: 'Low',
        status: 'Resolved',
        suspectName: 'Jordan Blake',
        investigator: 'Officer Ray Miller',
        deadline: new Date(Date.now() - 5 * 86400000),
        progress: 100,
        location: 'Civic Plaza, Metro City Hall',
        tags: ['Physical Security', 'Trespassing', 'Closed'],
      },
      {
        caseId: 'CASE-006',
        title: 'Maritime Narcotics Smuggling Nexus',
        description: 'Intelligence tip regarding commercial cargo vessel container tampering and distribution through front logistics firms.',
        category: 'Narcotics',
        priority: 'Critical',
        status: 'Under Investigation',
        suspectName: 'Marcus Webb',
        investigator: 'Det. Sarah Vance',
        deadline: new Date(Date.now() + 5 * 86400000),
        progress: 85,
        location: 'East Coast Container Terminal Berth 7',
        tags: ['Maritime', 'Narcotics', 'DEA Liaison', 'Interdiction'],
      },
      {
        caseId: 'CASE-007',
        title: 'Evidence Locker Chain-of-Custody Discrepancy',
        description: 'Audit discrepancy identified in Central Evidence Locker 4B involving unlogged custody transfer of encrypted storage drives.',
        category: 'Intelligence',
        priority: 'Medium',
        status: 'New',
        suspectName: 'Unknown',
        investigator: 'Internal Affairs Insp. Novak',
        deadline: new Date(Date.now() + 18 * 86400000),
        progress: 20,
        location: 'Central Precinct Headquarters',
        tags: ['Internal Affairs', 'Chain of Custody', 'Audit'],
      },
      {
        caseId: 'CASE-008',
        title: 'Offshore Ponzi & Securities Fraud Scheme',
        description: 'Multi-jurisdictional securities scheme soliciting investments into bogus green energy trusts through shell advisory firms.',
        category: 'Financial',
        priority: 'High',
        status: 'Under Investigation',
        suspectName: 'Elena Vasquez',
        investigator: 'Agent David Chen',
        deadline: new Date(Date.now() + 12 * 86400000),
        progress: 60,
        location: 'Grand Cayman / Metro Financial District',
        tags: ['Securities', 'Money Laundering', 'Shell Companies'],
      },
      {
        caseId: 'CASE-009',
        title: 'Dark Web Data Brokerage Exfiltration',
        description: 'Classified proprietary algorithmic trade models found offered on breach forums. Source traced to insider terminal credentials.',
        category: 'Cyber',
        priority: 'Critical',
        status: 'Under Investigation',
        suspectName: 'Kaelen Cross',
        investigator: 'Agent David Chen',
        deadline: new Date(Date.now() + 8 * 86400000),
        progress: 40,
        location: 'Quantum Trading Server Farm',
        tags: ['Insider Threat', 'Dark Web', 'TOR', 'IP Theft'],
      },
      {
        caseId: 'CASE-010',
        title: 'Cargo Manifest Forgery & Customs Diversion',
        description: 'Falsified maritime bills of lading routing high-value dual-use telecommunication hardware away from inspected ports.',
        category: 'Fraud',
        priority: 'Medium',
        status: 'Under Investigation',
        suspectName: 'Jordan Blake',
        investigator: 'Det. Sarah Vance',
        deadline: new Date(Date.now() + 25 * 86400000),
        progress: 30,
        location: 'Port Authority Cargo Gate 12',
        tags: ['Customs', 'Manifest', 'Export Control'],
      },
    ];

    const savedCases = await Case.insertMany(casesData);

    // 2. ENTITIES (22 connected entities)
    const entitiesData = [
      {
        entityId: 'ENT-001',
        name: 'Marcus Webb',
        type: 'Person',
        description: 'Primary person of interest in maritime logistics theft and luxury vehicle interception rings. Known aliases: "The Anchor", M. Weber.',
        metadata: { phone: '+1 (555) 438-9021', passport: 'USA-9821414', knownLocations: ['Harbor District', 'Midtown Docks'] },
        riskLevel: 'Critical',
        relatedCases: ['CASE-001', 'CASE-003', 'CASE-006'],
        tags: ['Primary Suspect', 'Logistics', 'Repeat Offender'],
      },
      {
        entityId: 'ENT-002',
        name: 'Elena Vasquez',
        type: 'Person',
        description: 'Financier and cryptographic system architect connected to synthetic ID syndicates and corporate BEC wire routing.',
        metadata: { phone: '+1 (555) 782-3490', email: 'e.vasquez@apexholdings.org', alias: 'Specter_9' },
        riskLevel: 'Critical',
        relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'],
        tags: ['Financier', 'Cyber Specialist', 'Shell Director'],
      },
      {
        entityId: 'ENT-003',
        name: 'Jordan Blake',
        type: 'Person',
        description: 'Logistics coordinator and freight handler previously observed at Harbor District gate security and city hall intrusion.',
        metadata: { phone: '+1 (555) 209-1144', badge: 'PORT-8891' },
        riskLevel: 'Medium',
        relatedCases: ['CASE-005', 'CASE-010'],
        tags: ['Inside Operative', 'Dockworker'],
      },
      {
        entityId: 'ENT-004',
        name: 'Kaelen Cross',
        type: 'Person',
        description: 'Former senior systems engineer at Northstar Tech, suspected of exfiltrating firmware builds and secure keys.',
        metadata: { phone: '+1 (555) 601-9988', pgpKey: '0x88F9A1B2C3D4' },
        riskLevel: 'High',
        relatedCases: ['CASE-009'],
        tags: ['Hacker', 'Data Broker'],
      },
      {
        entityId: 'ENT-005',
        name: 'Apex Holdings Ltd',
        type: 'Organization',
        description: 'Offshore shell conglomerate registered in Delaware with holding bank accounts in Zurich and Grand Cayman.',
        metadata: { regNumber: 'DE-882941-X', jurisdiction: 'Delaware / Cayman' },
        riskLevel: 'Critical',
        relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'],
        tags: ['Corporate Shell', 'Money Laundering'],
      },
      {
        entityId: 'ENT-006',
        name: 'Harbor Logistics Freight Co.',
        type: 'Organization',
        description: 'Maritime warehousing operator leasing Pier 42 facility where component thefts and unlogged containers occurred.',
        metadata: { license: 'DOT-449102', portPermit: 'PORT-NY-42' },
        riskLevel: 'High',
        relatedCases: ['CASE-001', 'CASE-006'],
        tags: ['Front Company', 'Warehousing'],
      },
      {
        entityId: 'ENT-007',
        name: 'Pier 42 Harbor Warehouse',
        type: 'Location',
        description: 'Primary location of initial electronic components break-in. 85,000 sq ft bonded customs storage.',
        metadata: { coordinates: '40.7128° N, 74.0060° W', securitySystem: 'CCTV + Bio-scanner' },
        riskLevel: 'Medium',
        relatedCases: ['CASE-001', 'CASE-006'],
        tags: ['Crime Scene', 'Harbor'],
      },
      {
        entityId: 'ENT-008',
        name: 'Apex Financial Tower',
        type: 'Location',
        description: 'High-rise commercial headquarters housing offices of Elena Vasquez and registered proxy agents.',
        metadata: { address: '700 Financial Boulevard, 9th Floor' },
        riskLevel: 'High',
        relatedCases: ['CASE-002', 'CASE-008'],
        tags: ['Target Facility', 'Financial'],
      },
      {
        entityId: 'ENT-009',
        name: 'Black BMW M5 (Plates: 7XYZ-89)',
        type: 'Vehicle',
        description: 'Surveillance vehicle captured on CCTV departing Pier 42 at 01:45 AM following vault alarms.',
        metadata: { vin: 'WBA53...0091', registeredTo: 'Apex Holdings Fleet' },
        riskLevel: 'High',
        relatedCases: ['CASE-001', 'CASE-003'],
        tags: ['Getaway Vehicle', 'Surveillance'],
      },
      {
        entityId: 'ENT-010',
        name: 'Encrypted Burner Phone (+1-555-438-9021)',
        type: 'Phone',
        description: 'Hardened voice-over-IP terminal recovered during vehicle interdiction; linked to Marcus Webb communications.',
        metadata: { imei: '864201048891223', carrier: 'Anonymous Satellite eSIM' },
        riskLevel: 'High',
        relatedCases: ['CASE-001', 'CASE-003', 'CASE-006'],
        tags: ['Comms', 'Forensics'],
      },
      {
        entityId: 'ENT-011',
        name: 'Encrypted Proton Email (v_elena@pm.me)',
        type: 'Email',
        description: 'Email identity used to coordinate synthetic identity loan disbursements and shell corporate filings.',
        metadata: { provider: 'Proton AG', creationIP: '185.220.101.5 (Tor Exit)' },
        riskLevel: 'High',
        relatedCases: ['CASE-002', 'CASE-004'],
        tags: ['Digital Identity', 'Dark Web'],
      },
      {
        entityId: 'ENT-012',
        name: 'Wire Transfer #WT-89410 ($1.25M)',
        type: 'Transaction',
        description: 'Wire originating from Apex Holdings Ltd to numbered Swiss IBAN account CH93-0000-8812.',
        metadata: { amount: '$1,250,000.00 USD', bank: 'Zurich Private Mercantile' },
        riskLevel: 'Critical',
        relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'],
        tags: ['Financial Fraud', 'Asset Flow'],
      },
      {
        entityId: 'ENT-013',
        name: 'Crypto Wallet 0x71C...4F9B (USDT)',
        type: 'Transaction',
        description: 'Tether multi-sig address receiving structured deposits matching vehicle theft sale proceeds.',
        metadata: { network: 'Ethereum', balance: '480,000 USDT' },
        riskLevel: 'High',
        relatedCases: ['CASE-003', 'CASE-009'],
        tags: ['Cryptocurrency', 'Blockchain'],
      },
      {
        entityId: 'ENT-014',
        name: 'Falsified Bill of Lading BL-4901',
        type: 'Document',
        description: 'Forged shipping manifest declaring container content as "Automotive Castings" instead of dual-use hardware.',
        metadata: { containerId: 'TGHU-992144', stamp: 'Forged Customs Seal' },
        riskLevel: 'High',
        relatedCases: ['CASE-006', 'CASE-010'],
        tags: ['Forgery', 'Manifest'],
      },
      {
        entityId: 'ENT-015',
        name: 'Recovered Thermal Cutting Rig',
        type: 'Evidence',
        description: 'Industrial exothermic torch system recovered abandoned near Harbor District stormwater canal.',
        metadata: { serial: 'TH-994-GER', fuelType: 'Oxygen-Acetylene' },
        riskLevel: 'Medium',
        relatedCases: ['CASE-001'],
        tags: ['Physical Tool', 'Crime Scene'],
      },
      {
        entityId: 'ENT-016',
        name: 'CAN-Bus Spoofing Hardware',
        type: 'Evidence',
        description: 'Custom micro-controller board programmed to bypass luxury vehicle immobilizer sensors.',
        metadata: { chipset: 'STM32F4', firmwareHash: 'E3B0C442...9821' },
        riskLevel: 'High',
        relatedCases: ['CASE-003'],
        tags: ['Cyber-Physical', 'Auto Theft'],
      },
      {
        entityId: 'ENT-017',
        name: 'Northstar Tech Campus',
        type: 'Location',
        description: 'Technology corridor campus where credential exfiltration and phishing targets were situated.',
        metadata: { address: '100 Innovation Way, Silicon Metro' },
        riskLevel: 'Low',
        relatedCases: ['CASE-004', 'CASE-009'],
        tags: ['Victim Organization', 'Corporate'],
      },
      {
        entityId: 'ENT-018',
        name: 'East Coast Container Berth 7',
        type: 'Location',
        description: 'Deepwater maritime docking station where contraband was offloaded under false documentation.',
        metadata: { dockDepth: '50ft', craneBay: 'C-14' },
        riskLevel: 'High',
        relatedCases: ['CASE-006', 'CASE-010'],
        tags: ['Maritime', 'Port'],
      },
      {
        entityId: 'ENT-019',
        name: 'Freightliner Heavy Hauler (Plates: 4TRK-01)',
        type: 'Vehicle',
        description: 'Commercial flatbed trailer utilized to transport sealed cargo containers from Pier 42 to secondary chop shops.',
        metadata: { make: 'Freightliner Cascadia', color: 'White' },
        riskLevel: 'Medium',
        relatedCases: ['CASE-001', 'CASE-006'],
        tags: ['Heavy Transport'],
      },
      {
        entityId: 'ENT-020',
        name: 'Encrypted USB Storage Key (Kingston IronKey)',
        type: 'Evidence',
        description: 'Hardware-encrypted thumb drive seized during vehicle stop containing synthetic bank profiles.',
        metadata: { capacity: '64 GB', encryption: 'XTS-AES 256' },
        riskLevel: 'Critical',
        relatedCases: ['CASE-002', 'CASE-007'],
        tags: ['Digital Evidence', 'Key Forensic'],
      },
      {
        entityId: 'ENT-021',
        name: 'Vessel MV Northern Star',
        type: 'Vehicle',
        description: 'Panamanian-flagged container vessel carrying flagged cargo units across transatlantic route.',
        metadata: { imo: '9314488', flag: 'Panama' },
        riskLevel: 'High',
        relatedCases: ['CASE-006', 'CASE-010'],
        tags: ['Cargo Ship', 'Maritime'],
      },
      {
        entityId: 'ENT-022',
        name: 'Midtown Underground Garage',
        type: 'Location',
        description: 'Commercial subterranean facility from which three luxury executive vehicles were stolen.',
        metadata: { levels: 'B1-B4', operator: 'MetroPark Central' },
        riskLevel: 'Low',
        relatedCases: ['CASE-003'],
        tags: ['Crime Scene'],
      },
    ];

    const savedEntities = await Entity.insertMany(entitiesData);

    // 3. RELATIONSHIPS (26 connected intelligence vectors)
    const relationshipsData = [
      // Marcus Webb connections
      { relationshipId: 'REL-001', sourceEntity: 'Marcus Webb', targetEntity: 'Encrypted Burner Phone (+1-555-438-9021)', type: 'Owned by', strength: 'strong', caseId: 'CASE-001', details: 'Direct subscriber registration link found on seized handset.' },
      { relationshipId: 'REL-002', sourceEntity: 'Encrypted Burner Phone (+1-555-438-9021)', targetEntity: 'Elena Vasquez', type: 'Contacted', strength: 'strong', caseId: 'CASE-001', details: '14 encrypted Signal call records between 23:00 and 02:00 on raid night.' },
      { relationshipId: 'REL-003', sourceEntity: 'Marcus Webb', targetEntity: 'Harbor Logistics Freight Co.', type: 'Associated with', strength: 'strong', caseId: 'CASE-001', details: 'Sub-contractor freight pass issued in Webb alias.' },
      { relationshipId: 'REL-004', sourceEntity: 'Marcus Webb', targetEntity: 'Black BMW M5 (Plates: 7XYZ-89)', type: 'Contacted', strength: 'strong', caseId: 'CASE-001', details: 'Observed operating vehicle leaving Pier 42 compound.' },
      { relationshipId: 'REL-005', sourceEntity: 'Black BMW M5 (Plates: 7XYZ-89)', targetEntity: 'Apex Holdings Ltd', type: 'Owned by', strength: 'strong', caseId: 'CASE-001', details: 'Commercial lease registered to Apex Holdings corporate entity.' },
      { relationshipId: 'REL-006', sourceEntity: 'Apex Holdings Ltd', targetEntity: 'Elena Vasquez', type: 'Owned by', strength: 'strong', caseId: 'CASE-002', details: 'Elena Vasquez listed as designated managing officer and sole signatory.' },
      { relationshipId: 'REL-007', sourceEntity: 'Elena Vasquez', targetEntity: 'Apex Financial Tower', type: 'Located at', strength: 'strong', caseId: 'CASE-002', details: 'Leases Executive Suite 900 on 5-year commercial contract.' },
      { relationshipId: 'REL-008', sourceEntity: 'Elena Vasquez', targetEntity: 'Encrypted Proton Email (v_elena@pm.me)', type: 'Associated with', strength: 'strong', caseId: 'CASE-002', details: 'Primary recovery address configured on Apex corporate portal.' },
      { relationshipId: 'REL-009', sourceEntity: 'Apex Holdings Ltd', targetEntity: 'Wire Transfer #WT-89410 ($1.25M)', type: 'Transferred to', strength: 'strong', caseId: 'CASE-002', details: 'Origin account debited for offshore remittance to Zurich.' },
      { relationshipId: 'REL-010', sourceEntity: 'Marcus Webb', targetEntity: 'Pier 42 Harbor Warehouse', type: 'Located at', strength: 'strong', caseId: 'CASE-001', details: 'Cell tower ping places burner handset at Pier 42 at 01:12 AM.' },
      { relationshipId: 'REL-011', sourceEntity: 'Pier 42 Harbor Warehouse', targetEntity: 'Recovered Thermal Cutting Rig', type: 'Evidence of', strength: 'strong', caseId: 'CASE-001', details: 'Tool discovered 300 meters from breached vault door.' },
      { relationshipId: 'REL-012', sourceEntity: 'Marcus Webb', targetEntity: 'Midtown Underground Garage', type: 'Located at', strength: 'moderate', caseId: 'CASE-003', details: 'Surveillance matches subject height and gait during vehicle entry.' },
      { relationshipId: 'REL-013', sourceEntity: 'Marcus Webb', targetEntity: 'CAN-Bus Spoofing Hardware', type: 'Associated with', strength: 'strong', caseId: 'CASE-003', details: 'Fingerprint match identified on module casing.' },
      { relationshipId: 'REL-014', sourceEntity: 'Elena Vasquez', targetEntity: 'Northstar Tech Campus', type: 'Mentioned in', strength: 'moderate', caseId: 'CASE-004', details: 'Phishing domain sender address spoofed Vasquez executive credential.' },
      { relationshipId: 'REL-015', sourceEntity: 'Marcus Webb', targetEntity: 'Jordan Blake', type: 'Connected through', strength: 'strong', caseId: 'CASE-006', details: 'Frequent communications regarding container shift schedules.' },
      { relationshipId: 'REL-016', sourceEntity: 'Jordan Blake', targetEntity: 'Harbor Logistics Freight Co.', type: 'Associated with', strength: 'strong', caseId: 'CASE-006', details: 'Full-time logistics dispatcher handling manifest intake.' },
      { relationshipId: 'REL-017', sourceEntity: 'Jordan Blake', targetEntity: 'Falsified Bill of Lading BL-4901', type: 'Evidence of', strength: 'strong', caseId: 'CASE-010', details: 'Digital terminal timestamp signed under Blake user login.' },
      { relationshipId: 'REL-018', sourceEntity: 'Falsified Bill of Lading BL-4901', targetEntity: 'Vessel MV Northern Star', type: 'Related to', strength: 'strong', caseId: 'CASE-006', details: 'Bill of lading covers cargo hold containers on MV Northern Star.' },
      { relationshipId: 'REL-019', sourceEntity: 'Vessel MV Northern Star', targetEntity: 'East Coast Container Berth 7', type: 'Located at', strength: 'strong', caseId: 'CASE-006', details: 'Berthing records show vessel docked April 4th through 8th.' },
      { relationshipId: 'REL-020', sourceEntity: 'Jordan Blake', targetEntity: 'Freightliner Heavy Hauler (Plates: 4TRK-01)', type: 'Contacted', strength: 'moderate', caseId: 'CASE-006', details: 'Dispatched flatbed trailer without gate inspection clearing.' },
      { relationshipId: 'REL-021', sourceEntity: 'Elena Vasquez', targetEntity: 'Encrypted USB Storage Key (Kingston IronKey)', type: 'Owned by', strength: 'strong', caseId: 'CASE-002', details: 'Serial key documented in Vasquez personal office inventory.' },
      { relationshipId: 'REL-022', sourceEntity: 'Kaelen Cross', targetEntity: 'Northstar Tech Campus', type: 'Associated with', strength: 'strong', caseId: 'CASE-009', details: 'Former senior engineer badge access logs.' },
      { relationshipId: 'REL-023', sourceEntity: 'Kaelen Cross', targetEntity: 'Crypto Wallet 0x71C...4F9B (USDT)', type: 'Transferred to', strength: 'strong', caseId: 'CASE-009', details: 'Wallet receiving payouts linked to Cross private key backup.' },
      { relationshipId: 'REL-024', sourceEntity: 'Elena Vasquez', targetEntity: 'Crypto Wallet 0x71C...4F9B (USDT)', type: 'Connected through', strength: 'moderate', caseId: 'CASE-004', details: 'Wallet interacted with smart contract funded by Apex affiliate.' },
      { relationshipId: 'REL-025', sourceEntity: 'Marcus Webb', targetEntity: 'East Coast Container Berth 7', type: 'Located at', strength: 'strong', caseId: 'CASE-006', details: 'Observed meeting MV Northern Star mate at dock perimeter.' },
      { relationshipId: 'REL-026', sourceEntity: 'Wire Transfer #WT-89410 ($1.25M)', targetEntity: 'Elena Vasquez', type: 'Related to', strength: 'strong', caseId: 'CASE-008', details: 'Vasquez signed authorization memorandum for capital transfer.' },
    ];

    await Relationship.insertMany(relationshipsData);

    // 4. EVIDENCE (16 items)
    const evidenceData = [
      {
        evidenceId: 'EVD-001',
        name: 'Pier 42 Vault Door Cutting Swarf & Residue',
        type: 'Physical Evidence',
        description: 'Exothermic metal slag and magnesium wire fragments gathered from safe door perimeter.',
        caseId: 'CASE-001',
        uploadedBy: 'Forensics Specialist Ramos',
        status: 'Verified',
        relatedEntities: ['Marcus Webb', 'Recovered Thermal Cutting Rig'],
      },
      {
        evidenceId: 'EVD-002',
        name: 'CCTV Exterior Gate 4 Footage (MP4)',
        type: 'Video',
        description: 'High-definition 4K footage capturing black BMW M5 exiting compound without lights at 01:48 AM.',
        caseId: 'CASE-001',
        uploadedBy: 'Det. Sarah Vance',
        status: 'Verified',
        relatedEntities: ['Black BMW M5 (Plates: 7XYZ-89)', 'Pier 42 Harbor Warehouse'],
      },
      {
        evidenceId: 'EVD-003',
        name: 'Burner Handset Cellular Tower Extraction (ZIP)',
        type: 'Digital Record',
        description: 'Full UFED forensic extraction of VoLTE burner phone showing 42 contact records and encrypted SMS.',
        caseId: 'CASE-001',
        uploadedBy: 'Cyber Tech Lin',
        status: 'In Analysis',
        relatedEntities: ['Encrypted Burner Phone (+1-555-438-9021)', 'Marcus Webb', 'Elena Vasquez'],
      },
      {
        evidenceId: 'EVD-004',
        name: 'Apex Holdings Cayman Banking Subpoena Return',
        type: 'Document',
        description: 'Certified financial statements detailing $1.25M wire outflow and beneficial ownership documentation.',
        caseId: 'CASE-002',
        uploadedBy: 'Agent David Chen',
        status: 'Verified',
        relatedEntities: ['Apex Holdings Ltd', 'Elena Vasquez', 'Wire Transfer #WT-89410 ($1.25M)'],
      },
      {
        evidenceId: 'EVD-005',
        name: 'Synthetic Credit Application Packet (Batch #9)',
        type: 'Document',
        description: '45 fraudulent loan files utilizing fictitious social security numbers matching deceased individuals.',
        caseId: 'CASE-002',
        uploadedBy: 'Agent David Chen',
        status: 'Collected',
        relatedEntities: ['Elena Vasquez', 'Apex Holdings Ltd'],
      },
      {
        evidenceId: 'EVD-006',
        name: 'CAN-Bus Inverter & Key Emulator Module',
        type: 'Digital Record',
        description: 'Captured hardware tool extracted from dashboard wiring harness of recovered luxury SUV.',
        caseId: 'CASE-003',
        uploadedBy: 'Det. Sarah Vance',
        status: 'Verified',
        relatedEntities: ['Marcus Webb', 'CAN-Bus Spoofing Hardware'],
      },
      {
        evidenceId: 'EVD-007',
        name: 'Midtown Garage Surveillance Tape Roll 3',
        type: 'Video',
        description: 'Overhead camera recording two individuals in dark hoodies programming vehicle through OBD port.',
        caseId: 'CASE-003',
        uploadedBy: 'Officer Ray Miller',
        status: 'Collected',
        relatedEntities: ['Midtown Underground Garage', 'Marcus Webb'],
      },
      {
        evidenceId: 'EVD-008',
        name: 'Phishing Email Header Logs & SPF Mismatch',
        type: 'Digital Record',
        description: 'Raw RFC-822 headers demonstrating DKIM forgery and originating IP belonging to VPN exit node.',
        caseId: 'CASE-004',
        uploadedBy: 'Cyber Tech Lin',
        status: 'Verified',
        relatedEntities: ['Encrypted Proton Email (v_elena@pm.me)', 'Elena Vasquez'],
      },
      {
        evidenceId: 'EVD-009',
        name: 'City Hall Server Access Audit Dump',
        type: 'Document',
        description: 'Active Directory domain controller logs showing physical console logon attempts at 02:22 AM.',
        caseId: 'CASE-005',
        uploadedBy: 'Officer Ray Miller',
        status: 'Archived',
        relatedEntities: ['Jordan Blake'],
      },
      {
        evidenceId: 'EVD-010',
        name: 'Maritime Cargo Manifest BL-4901 Original',
        type: 'Document',
        description: 'Stamped hard-copy manifest with mismatched weight discrepancy (14.2 tons declared vs 28.5 tons actual).',
        caseId: 'CASE-006',
        uploadedBy: 'Det. Sarah Vance',
        status: 'Verified',
        relatedEntities: ['Falsified Bill of Lading BL-4901', 'MV Northern Star', 'Jordan Blake'],
      },
      {
        evidenceId: 'EVD-011',
        name: 'Narcotics Swab Analysis Laboratory Report',
        type: 'Physical Evidence',
        description: 'Chemical spectrometer confirmation of cocaine residue on structural bulkheads of container TGHU-992144.',
        caseId: 'CASE-006',
        uploadedBy: 'DEA Forensic Lab',
        status: 'Verified',
        relatedEntities: ['Marcus Webb', 'East Coast Container Berth 7'],
      },
      {
        evidenceId: 'EVD-012',
        name: 'Internal Audit Custody Seal Photographs',
        type: 'Image',
        description: 'High-resolution images showing tampered barcode tape on evidence box holding encrypted storage drives.',
        caseId: 'CASE-007',
        uploadedBy: 'Insp. Novak',
        status: 'Collected',
        relatedEntities: ['Encrypted USB Storage Key (Kingston IronKey)'],
      },
      {
        evidenceId: 'EVD-013',
        name: 'Ponzi Investment Marketing Brochure & Contract',
        type: 'Document',
        description: 'Glossy pitch deck promising 28% annual fixed yield backed by non-existent geothermal installations.',
        caseId: 'CASE-008',
        uploadedBy: 'Agent David Chen',
        status: 'Verified',
        relatedEntities: ['Apex Holdings Ltd', 'Elena Vasquez'],
      },
      {
        evidenceId: 'EVD-014',
        name: 'Breach Forum Telegram Chat Export',
        type: 'Digital Record',
        description: 'Scraped channel conversations between user "Specter_9" and dark web broker discussing trade secrets.',
        caseId: 'CASE-009',
        uploadedBy: 'Agent David Chen',
        status: 'In Analysis',
        relatedEntities: ['Kaelen Cross', 'Elena Vasquez'],
      },
      {
        evidenceId: 'EVD-015',
        name: 'Kingston IronKey Drive Image (DD Format)',
        type: 'Digital Record',
        description: 'Bitstream image copy of seized hardware key containing 12,000 synthetic banking identities.',
        caseId: 'CASE-002',
        uploadedBy: 'Cyber Tech Lin',
        status: 'Verified',
        relatedEntities: ['Encrypted USB Storage Key (Kingston IronKey)', 'Elena Vasquez'],
      },
      {
        evidenceId: 'EVD-016',
        name: 'Surveillance Audio Wiretap Excerpt #4',
        type: 'Audio',
        description: 'Intercepted phone dialogue discussing delivery ETA at Port Gate 12 with reference to "The Anchor".',
        caseId: 'CASE-006',
        uploadedBy: 'Det. Sarah Vance',
        status: 'Verified',
        relatedEntities: ['Marcus Webb', 'Jordan Blake'],
      },
    ];

    await Evidence.insertMany(evidenceData);

    // 5. TIMELINE EVENTS (21 chronological events)
    const timelineData = [
      {
        eventId: 'EVT-001',
        caseId: 'CASE-001',
        date: new Date('2026-03-24T00:45:00Z'),
        time: '12:45 AM',
        eventType: 'Movement',
        description: 'Black BMW M5 detected idling outside Harbor Logistics Gate 4 perimeter fence.',
        relatedEntity: 'Black BMW M5 (Plates: 7XYZ-89)',
        location: 'Pier 42 Harbor Warehouse',
      },
      {
        eventId: 'EVT-002',
        caseId: 'CASE-001',
        date: new Date('2026-03-24T01:12:00Z'),
        time: '01:12 AM',
        eventType: 'Incident',
        description: 'Intrusion alarm tripped on Vault 4B; perimeter sensors cut with wire snips.',
        relatedEntity: 'Marcus Webb',
        location: 'Pier 42 Harbor Warehouse',
      },
      {
        eventId: 'EVT-003',
        caseId: 'CASE-001',
        date: new Date('2026-03-24T01:38:00Z'),
        time: '01:38 AM',
        eventType: 'Contact',
        description: 'Burner phone initiates encrypted outbound call to Elena Vasquez contact handle.',
        relatedEntity: 'Encrypted Burner Phone (+1-555-438-9021)',
        location: 'Harbor District',
      },
      {
        eventId: 'EVT-004',
        caseId: 'CASE-001',
        date: new Date('2026-03-24T04:15:00Z'),
        time: '04:15 AM',
        eventType: 'Evidence Upload',
        description: 'Physical recovery of abandoned thermal cutting torch and magnesium rod remnants.',
        relatedEntity: 'Recovered Thermal Cutting Rig',
        location: 'Pier 42 Drainage Canal',
      },
      {
        eventId: 'EVT-005',
        caseId: 'CASE-003',
        date: new Date('2026-03-25T21:10:00Z'),
        time: '09:10 PM',
        eventType: 'Incident',
        description: 'Two luxury SUVs stolen from Midtown garage using electronic signal amplifier.',
        relatedEntity: 'Marcus Webb',
        location: 'Midtown Underground Garage',
      },
      {
        eventId: 'EVT-006',
        caseId: 'CASE-003',
        date: new Date('2026-03-26T11:00:00Z'),
        time: '11:00 AM',
        eventType: 'Evidence Upload',
        description: 'CAN-bus emulator board recovered from abandoned decoy vehicle on Route 9.',
        relatedEntity: 'CAN-Bus Spoofing Hardware',
        location: 'Route 9 Northbound',
      },
      {
        eventId: 'EVT-007',
        caseId: 'CASE-002',
        date: new Date('2026-03-28T09:30:00Z'),
        time: '09:30 AM',
        eventType: 'Transaction',
        description: 'Wire transfer #WT-89410 initiated from Apex Holdings account for $1.25M.',
        relatedEntity: 'Wire Transfer #WT-89410 ($1.25M)',
        location: 'Apex Financial Tower',
      },
      {
        eventId: 'EVT-008',
        caseId: 'CASE-002',
        date: new Date('2026-03-28T14:45:00Z'),
        time: '02:45 PM',
        eventType: 'Finding Added',
        description: 'Investigator discovers beneficial owner of Apex Holdings is Elena Vasquez.',
        relatedEntity: 'Elena Vasquez',
        location: 'Apex Financial Tower',
      },
      {
        eventId: 'EVT-009',
        caseId: 'CASE-004',
        date: new Date('2026-03-29T08:15:00Z'),
        time: '08:15 AM',
        eventType: 'Communication',
        description: 'Phishing campaign launched targeting 48 senior financial officers at Northstar Tech.',
        relatedEntity: 'Encrypted Proton Email (v_elena@pm.me)',
        location: 'Northstar Tech Campus',
      },
      {
        eventId: 'EVT-010',
        caseId: 'CASE-004',
        date: new Date('2026-03-30T16:20:00Z'),
        time: '04:20 PM',
        eventType: 'Finding Added',
        description: 'Cyber unit isolates malware payload confirming signature match to Specter_9 group.',
        relatedEntity: 'Elena Vasquez',
        location: 'Cyber Operations Center',
      },
      {
        eventId: 'EVT-011',
        caseId: 'CASE-005',
        date: new Date('2026-04-01T02:20:00Z'),
        time: '02:20 AM',
        eventType: 'Incident',
        description: 'Physical intrusion detected at City Hall basement terminals; Jordan Blake captured on camera.',
        relatedEntity: 'Jordan Blake',
        location: 'Civic Plaza, Metro City Hall',
      },
      {
        eventId: 'EVT-012',
        caseId: 'CASE-008',
        date: new Date('2026-04-02T13:00:00Z'),
        time: '01:00 PM',
        eventType: 'Interview',
        description: 'Subpoenaed bank compliance officer confirms Vasquez personal presence during account setups.',
        relatedEntity: 'Elena Vasquez',
        location: 'Federal Courthouse',
      },
      {
        eventId: 'EVT-013',
        caseId: 'CASE-006',
        date: new Date('2026-04-04T06:00:00Z'),
        time: '06:00 AM',
        eventType: 'Movement',
        description: 'Container ship MV Northern Star berths at East Coast Container Terminal Berth 7.',
        relatedEntity: 'Vessel MV Northern Star',
        location: 'East Coast Container Berth 7',
      },
      {
        eventId: 'EVT-014',
        caseId: 'CASE-006',
        date: new Date('2026-04-04T18:30:00Z'),
        time: '06:30 PM',
        eventType: 'Contact',
        description: 'Wiretap captures dispatcher Jordan Blake alerting Marcus Webb regarding customs schedule.',
        relatedEntity: 'Marcus Webb',
        location: 'Harbor Logistics Yard',
      },
      {
        eventId: 'EVT-015',
        caseId: 'CASE-006',
        date: new Date('2026-04-05T03:15:00Z'),
        time: '03:15 AM',
        eventType: 'Incident',
        description: 'Federal joint task force intercepts Container TGHU-992144; positive swab for narcotics.',
        relatedEntity: 'Marcus Webb',
        location: 'Port Authority Gate 12',
      },
      {
        eventId: 'EVT-016',
        caseId: 'CASE-010',
        date: new Date('2026-04-05T10:00:00Z'),
        time: '10:00 AM',
        eventType: 'Evidence Upload',
        description: 'Falsified bill of lading seized from dispatch office computer terminal.',
        relatedEntity: 'Falsified Bill of Lading BL-4901',
        location: 'Harbor Logistics Office',
      },
      {
        eventId: 'EVT-017',
        caseId: 'CASE-007',
        date: new Date('2026-04-06T09:00:00Z'),
        time: '09:00 AM',
        eventType: 'Incident',
        description: 'Quarterly evidence audit red-flags unlogged checkout of encrypted hardware drives.',
        relatedEntity: 'Encrypted USB Storage Key (Kingston IronKey)',
        location: 'Central Precinct Headquarters',
      },
      {
        eventId: 'EVT-018',
        caseId: 'CASE-009',
        date: new Date('2026-04-07T15:30:00Z'),
        time: '03:30 PM',
        eventType: 'Transaction',
        description: 'Undercover agent initiates test escrow purchase of proprietary trade model files on Darknet.',
        relatedEntity: 'Crypto Wallet 0x71C...4F9B (USDT)',
        location: 'Dark Web Relay',
      },
      {
        eventId: 'EVT-019',
        caseId: 'CASE-009',
        date: new Date('2026-04-07T22:15:00Z'),
        time: '10:15 PM',
        eventType: 'Finding Added',
        description: 'PGP key on breach forum listing matches former employee Kaelen Cross code signatures.',
        relatedEntity: 'Kaelen Cross',
        location: 'Cyber Operations Center',
      },
      {
        eventId: 'EVT-020',
        caseId: 'CASE-002',
        date: new Date('2026-04-08T11:45:00Z'),
        time: '11:45 AM',
        eventType: 'Evidence Upload',
        description: 'IronKey drive successfully decrypted revealing 12,000 synthetic banking identity profiles.',
        relatedEntity: 'Encrypted USB Storage Key (Kingston IronKey)',
        location: 'Digital Forensics Unit',
      },
      {
        eventId: 'EVT-021',
        caseId: 'CASE-001',
        date: new Date('2026-04-08T16:00:00Z'),
        time: '04:00 PM',
        eventType: 'Finding Added',
        description: 'Forensics matches DNA on thermal torch handle to Marcus Webb criminal databank entry.',
        relatedEntity: 'Marcus Webb',
        location: 'State Crime Lab',
      },
    ];

    await TimelineEvent.insertMany(timelineData);

    // 6. INVESTIGATIONS (One per case)
    const investigationsData = casesData.map(c => ({
      investigationId: `INV-${c.caseId}`,
      caseId: c.caseId,
      title: `Investigation: ${c.title}`,
      status: c.status === 'Resolved' || c.status === 'Closed' ? 'Concluded' : 'Active',
      leadInvestigator: c.investigator,
      objectives: [
        'Establish forensic timeline and physical evidence chain',
        'Map communication records and financial wire transfers',
        'Trace organizational connections through shell corporations',
      ],
      findings: [
        {
          text: `Primary subject identified as ${c.suspectName} through multi-agency biometric and communication records.`,
          author: c.investigator,
          confidence: 'High',
          timestamp: new Date(Date.now() - 3 * 86400000),
        },
        {
          text: `Connected relationship established with auxiliary entities in Metro District and offshore jurisdictions.`,
          author: c.investigator,
          confidence: 'Verified',
          timestamp: new Date(Date.now() - 1 * 86400000),
        },
      ],
      hypotheses: [
        {
          text: `${c.suspectName} functions as operational cell leader coordinating through anonymous messaging relays.`,
          status: 'Validated',
          likelihood: 'High',
        },
        {
          text: `Capital from incident was laundered through Apex Holdings offshore accounts.`,
          status: 'Evaluating',
          likelihood: 'Moderate',
        },
      ],
      tasks: [
        { title: 'Subpoena cell tower metadata for incident timeframe', assignedTo: c.investigator, status: 'Completed' },
        { title: 'Interview registered owners of surveillance vehicles', assignedTo: c.investigator, status: 'In Progress' },
        { title: 'Prepare grand jury indictment package', assignedTo: c.investigator, status: 'Pending' },
      ],
      notes: [
        { text: `Urgent attention required on cross-border wire documentation.`, author: c.investigator, createdAt: new Date() },
      ],
      activity: [
        { action: 'Investigation Initialized', details: `Case ${c.caseId} assigned to ${c.investigator}`, user: 'System', timestamp: new Date(Date.now() - 10 * 86400000) },
        { action: 'Forensic Link Confirmed', details: `Corroborating physical and digital records logged`, user: c.investigator, timestamp: new Date(Date.now() - 2 * 86400000) },
      ],
    }));

    await Investigation.insertMany(investigationsData);

    // 7. ALERTS (10 realistic intelligence alerts)
    const alertsData = [
      {
        alertId: 'ALT-001',
        type: 'critical',
        title: 'Repeat Suspect Detected Across 3 Active Cases',
        message: 'Marcus Webb appears in CASE-001, CASE-003, and CASE-006. Serial nexus identified between cargo theft and narcotics interdiction.',
        caseId: 'CASE-001',
        relatedCases: ['CASE-001', 'CASE-003', 'CASE-006'],
        category: 'Repeat Suspect',
        isRead: false,
      },
      {
        alertId: 'ALT-002',
        type: 'critical',
        title: 'High-Value Offshore Wire Transfer Flagged',
        message: 'Wire Transfer #WT-89410 for $1,250,000 matches FinCEN threshold alerts linked to Apex Holdings Ltd.',
        caseId: 'CASE-002',
        relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'],
        category: 'Pattern Discovered',
        isRead: false,
      },
      {
        alertId: 'ALT-003',
        type: 'high',
        title: 'Multi-Case Network Hub: Elena Vasquez',
        message: 'Elena Vasquez connects 3 active high-priority cases (Synthetic ID, Corporate Fraud, Securities Scheme).',
        caseId: 'CASE-002',
        relatedCases: ['CASE-002', 'CASE-004', 'CASE-008'],
        category: 'Repeat Suspect',
        isRead: false,
      },
      {
        alertId: 'ALT-004',
        type: 'high',
        title: 'Container Interdiction Deadline Approaching',
        message: 'Statutory 72-hour detention hold on MV Northern Star container cargo expires in 28 hours.',
        caseId: 'CASE-006',
        relatedCases: ['CASE-006'],
        category: 'High Priority',
        isRead: false,
      },
      {
        alertId: 'ALT-005',
        type: 'warning',
        title: 'Chain-of-Custody Discrepancy Red-Flagged',
        message: 'Internal Affairs logged an audit mismatch on storage drive evidence in Central Locker 4B.',
        caseId: 'CASE-007',
        relatedCases: ['CASE-007'],
        category: 'New Evidence',
        isRead: false,
      },
      {
        alertId: 'ALT-006',
        type: 'warning',
        title: 'CAN-Bus Hardware Match Identified',
        message: 'Spoofing microcontroller firmware recovered in CASE-003 matches tools previously seized by State Police.',
        caseId: 'CASE-003',
        relatedCases: ['CASE-003'],
        category: 'New Evidence',
        isRead: true,
      },
      {
        alertId: 'ALT-007',
        type: 'critical',
        title: 'Classified Trade Algorithm Exfiltration Alert',
        message: 'Tor network broker post confirmed offering Northstar Tech trade models in exchange for Tether.',
        caseId: 'CASE-009',
        relatedCases: ['CASE-009', 'CASE-004'],
        category: 'High Priority',
        isRead: false,
      },
      {
        alertId: 'ALT-008',
        type: 'info',
        title: 'Municipal Intrusion Case Concluded',
        message: 'CASE-005 successfully resolved and archived with formal charges filed against Jordan Blake.',
        caseId: 'CASE-005',
        relatedCases: ['CASE-005'],
        category: 'General',
        isRead: true,
      },
      {
        alertId: 'ALT-009',
        type: 'high',
        title: 'Decrypted IronKey Yields 12,000 Profiles',
        message: 'Digital forensics unit finalized full extraction of decrypted financial credentials.',
        caseId: 'CASE-002',
        relatedCases: ['CASE-002'],
        category: 'New Evidence',
        isRead: false,
      },
      {
        alertId: 'ALT-010',
        type: 'info',
        title: 'Investigation Backlog Notice',
        message: '7 cases currently Under Investigation require milestone status review before end-of-month audit.',
        caseId: '',
        relatedCases: [],
        category: 'Backlog',
        isRead: false,
      },
    ];

    await Alert.insertMany(alertsData);

    // 8. ACTIVITIES
    const activitiesData = [
      { user: 'Det. Sarah Vance', action: 'Biometric Verification', caseId: 'CASE-001', details: 'Confirmed DNA match on thermal cutter to Marcus Webb' },
      { user: 'Agent David Chen', action: 'Subpoena Filed', caseId: 'CASE-002', details: 'Served grand jury subpoena on Apex Financial Tower corporate management' },
      { user: 'Insp. Novak', action: 'Internal Audit', caseId: 'CASE-007', details: 'Secured video records for Central Evidence Locker 4B' },
      { user: 'Cyber Tech Lin', action: 'Forensic Extraction', caseId: 'CASE-002', details: 'Completed decryption of IronKey cryptographic volume' },
      { user: 'Det. Sarah Vance', action: 'Interdiction Operation', caseId: 'CASE-006', details: 'Seized narcotics shipment at Berth 7 container yard' },
    ];

    await Activity.insertMany(activitiesData);

    res.json({
      success: true,
      message: 'CaseChain database successfully initialized with rich connected fictional demo data!',
      counts: {
        cases: casesData.length,
        entities: entitiesData.length,
        relationships: relationshipsData.length,
        evidence: evidenceData.length,
        timelineEvents: timelineData.length,
        investigations: investigationsData.length,
        alerts: alertsData.length,
      },
    });
  } catch (err) {
    console.error('seedDatabase error:', err);
    res.status(500).json({ success: false, message: 'Server error seeding database', error: err.message });
  }
};
